---
# Set this to the user ansible is logging in as - should have root
# or sudo access
mysql_user_home: /opt/stack
mysql_user_name: stack
mysql_user_password: devstack

# The default root user installed by mysql - almost always root
mysql_root_home: /opt/stack
mysql_root_username: root
mysql_root_password: devstack

mysql_enabled_on_startup: true

# Define a custom list of packages to install; if none provided, the default
# package list from vars/[OS-family].yml will be used.
# mysql_packages:
#   - mysql
#   - mysql-server
#   - MySQL-python

mysql_python_package_debian: python3-mysqldb

# MySQL connection settings.
mysql_port: "3306"
mysql_bind_address: '0.0.0.0'
mysql_skip_name_resolve: false
mysql_datadir: /var/lib/mysql
mysql_sql_mode: ~